///<reference types="Cypress" />
describe('RegAccount', function () {
    it('VRigForm',function () 
   {
       cy.visit('https://www.nopcommerce.com/en/register?returnUrl=%2Fen')
       cy.get('#FirstName').type("Eslam")
       cy.get('#LastName').type("Sofian")
       cy.get('#Email').type("alsofian92@gmail.com")
       cy.get('#ConfirmEmail').type("alsofian92@gmail.com")
       cy.get('#Username').type("sos")
       cy.server()
       cy.route('POST','/en/customer/check-username-availability').as('feedback')
       cy.get('#check-availability-button').click()
       cy.wait('@feedback')
       cy.get('#username-availabilty').should('be.visible').contains('Username not available')
       cy.get('#CountryId').select('Egypt').should('have.value','299')
       cy.get('#TimeZoneId').select('(UTC+02:00) Cairo').should('have.value','Egypt Standard Time')
       cy.get('#Password').type("s@123456789")
       cy.get('#ConfirmPassword').type("s@123456789")
       cy.get('#Details_CompanyIndustryId').select('Provides deployment, customization and integration services to merchants').should('have.value','1')
       cy.get('#Details_CompanyRoleId').select('Technical developer').should('have.value','10')
       cy.get('#Details_WebsitesDevelopmentPeriodId').select('1').should('have.value','1')
       cy.get(':nth-child(8) > .gender > :nth-child(1) > .custom-control-label').click()
       cy.get('#Details_CompanySizeId').select('1').should('have.value','1')
       cy.get('#Details_CompanyWebsiteUrl').type("https://www.noe.com")
       cy.get('#register-button').should('be.visible').click()
       cy.url().should('include','register')
       cy.get('div.message-error.validation-summary-errors > ul > li:nth-child(2)').contains('Please enter all the required information below')
       cy.get('div.message-error.validation-summary-errors > ul > li:nth-child(1)').contains('The specified email already exists')
       
   })
})