///<reference types="Cypress" />
describe('VerPageEli', function () {
  it('VTitle',function () 
  {
      cy.visit('https://www.nopcommerce.com/en/register?returnUrl=%2Fen')
      cy.title().should('eq','Register - nopCommerce')
      cy.url().should('include','register')
  })
  it('VLabel',function () 
  {
      cy.get('form').contains('First name:')
      cy.get('form').contains('Last name:')
      cy.get('form').contains('Email:')
      cy.get('form').contains('Confirm email:')
      cy.get('form').contains('Username:')
      cy.get('form').contains('Country:')
      cy.get('form').contains('Time zone:')
      cy.get('form').contains('Password:')
      cy.get('form').contains('Confirm password:')
      cy.get('form').contains('My company primarily:')
      cy.get('form').contains('My main activity in the company is:')
      cy.get('form').contains('How many people work for your company?')
      cy.get('form').contains('My company’s website (if any):')
  })
  it('VInput',function () 
  {
      cy.get('#FirstName').should('be.visible').should('be.enabled')
      cy.get('#LastName').should('be.visible').should('be.enabled')
      cy.get('#Email').should('be.visible').should('be.enabled')
      cy.get('#ConfirmEmail').should('be.visible').should('be.enabled')
      cy.get('#Username').should('be.visible').should('be.enabled')
      cy.get('#check-availability-button').should('be.visible')
      cy.get('#CountryId').should('be.visible').should('be.enabled')
      cy.get('#TimeZoneId').should('be.visible').should('be.enabled')
      cy.get('#Newsletter').should('be.visible').should('be.enabled')
      cy.get('#Password').should('be.visible').should('be.enabled')
      cy.get('#ConfirmPassword').should('be.visible').should('be.enabled')
      cy.get('#Details_CompanyIndustryId').should('be.visible').should('be.enabled')
      cy.get('#Details_CompanyRoleId').should('be.visible').should('be.enabled')
      cy.get('#Details_CompanySizeId').should('be.visible').should('be.enabled')
      cy.get('#Details_CompanyWebsiteUrl').should('be.visible').should('be.enabled')
      cy.get('#register-button').should('be.visible').should('be.enabled')
  })
  it('VPageAddress',function () 
  {
       cy.get('h1').contains('Register')
  })
  
  it('VLogoLink',function () 
  {
      cy.get('.desktop-logo').click()
      cy.title().should('eq','Free and open-source eCommerce platform. ASP.NET based shopping cart. - nopCommerce')
      cy.go('back')
      cy.title().should('eq','Register - nopCommerce')
  })
})